blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/refringe/eslint-plugin-switch-allman/discussions
    about: Ask questions and discuss ideas here.
